# Generated by Django 4.1.7 on 2023-03-13 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 13, 16, 48, 42, 965910))),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
