# Generated by Django 4.1.7 on 2023-03-15 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 15, 15, 14, 8, 697486)),
        ),
    ]
