# Generated by Django 4.1.5 on 2023-03-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('productprice', models.IntegerField()),
                ('productrame', models.CharField(max_length=50)),
                ('productcatagory', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='productadmin',
        ),
    ]
